/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    participants: Participant;
    inscriptions: Inscription;
    paiements: Paiement;
    sessions: Session;
    intervenants: Intervenant;
    sponsors: Sponsor;
    editions: Edition;
    articles: Article;
    abonnes: Abonne;
    'codes-promo': CodesPromo;
    brouillons: Brouillon;
    epinglettes: Epinglette;
    reservations: Reservation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    inscriptions: InscriptionsSelect<false> | InscriptionsSelect<true>;
    paiements: PaiementsSelect<false> | PaiementsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    intervenants: IntervenantsSelect<false> | IntervenantsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    editions: EditionsSelect<false> | EditionsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    abonnes: AbonnesSelect<false> | AbonnesSelect<true>;
    'codes-promo': CodesPromoSelect<false> | CodesPromoSelect<true>;
    brouillons: BrouillonsSelect<false> | BrouillonsSelect<true>;
    epinglettes: EpinglettesSelect<false> | EpinglettesSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    boutique: Boutique;
  };
  globalsSelect: {
    boutique: BoutiqueSelect<false> | BoutiqueSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Qui peut se connecter à cette administration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nom?: string | null;
  role?: ('admin' | 'editeur') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos et fichiers réutilisables dans les articles et les fiches.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Une fiche par personne, créée automatiquement à l'inscription. Ne pas créer à la main.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  prenom: string;
  nom: string;
  email: string;
  telephone: string;
  pays?: string | null;
  ville?: string | null;
  club?: string | null;
  districtRole?: string | null;
  langue?: ('fr' | 'en') | null;
  regimeAlimentaire?: string | null;
  besoinsAccessibilite?: string | null;
  premiereConference?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Créées par le tunnel du site. Vous pouvez corriger un statut, jamais un montant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscriptions".
 */
export interface Inscription {
  id: number;
  participant: number | Participant;
  categorie: 'early' | 'standard' | 'late' | 'etudiant' | 'delegation' | 'vip';
  montant: number;
  devise?: ('XOF' | 'USD' | 'EUR') | null;
  statut?: ('en_attente' | 'payee' | 'annulee' | 'remboursee') | null;
  optionsSelectionnees?: ('excursions' | 'gala' | 'totebag')[] | null;
  codePromo?: string | null;
  /**
   * 1 en individuel, N en délégation
   */
  nombreParticipants?: number | null;
  membres?:
    | {
        prenom?: string | null;
        nom?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  modePaiement?: ('fedapay' | 'virement' | 'sur_place') | null;
  /**
   * Canal choisi à l'étape paiement
   */
  canal?: ('mtn' | 'moov' | 'carte') | null;
  qrToken?: string | null;
  checkedInAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trace de chaque transaction. Écrit automatiquement par le prestataire de paiement — lecture seule en pratique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paiements".
 */
export interface Paiement {
  id: number;
  inscription: number | Inscription;
  fournisseur: 'fedapay' | 'kkiapay' | 'stripe';
  referenceExterne?: string | null;
  montant: number;
  devise?: ('XOF' | 'USD' | 'EUR') | null;
  statut?: ('initie' | 'approuve' | 'refuse' | 'annule') | null;
  payloadWebhook?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Le programme affiché sur le site public, jour par jour.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  titre: string;
  resume?: string | null;
  type: 'keynote' | 'atelier' | 'panel' | 'concours' | 'ceremonie' | 'business' | 'social' | 'pause';
  debut: string;
  fin?: string | null;
  salle?: string | null;
  langue?: ('fr' | 'en' | 'bilingue') | null;
  capacite?: number | null;
  intervenants?: (number | Intervenant)[] | null;
  supportUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les conférenciers affichés sur la page Intervenants et sur l'accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intervenants".
 */
export interface Intervenant {
  id: number;
  nom: string;
  /**
   * URL de la fiche, ex. aichatou-dossou
   */
  slug: string;
  titre?: string | null;
  bio?: string | null;
  pays?: string | null;
  photo?: (number | null) | Media;
  keynote?: boolean | null;
  distinctions?:
    | {
        distinction?: string | null;
        id?: string | null;
      }[]
    | null;
  reseaux?:
    | {
        plateforme?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les partenaires affichés en bas de l'accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  nom: string;
  palier: 'platine' | 'or' | 'argent' | 'bronze' | 'institutionnel';
  logo?: (number | null) | Media;
  siteUrl?: string | null;
  description?: string | null;
  contreparties?:
    | {
        contrepartie?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Une édition regroupe plusieurs articles du magazine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions".
 */
export interface Edition {
  id: number;
  titre: string;
  /**
   * URL stable de l'édition, ex. early-bird-2026
   */
  slug: string;
  type: 'early-bird' | 'officiel' | 'post-conference';
  description?: string | null;
  couverture?: (number | null) | Media;
  publieLe: string;
  /**
   * PDF haute définition optionnel
   */
  pdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les articles du magazine. Rattachez chacun à une édition.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titre: string;
  slug: string;
  edition: number | Edition;
  chapo: string;
  corps: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  auteur: string;
  rubrique: 'portrait' | 'destination' | 'conference' | 'district' | 'art-oratoire';
  imageCouverture?: (number | null) | Media;
  /**
   * Minutes — calculé automatiquement si vide
   */
  tempsLecture?: number | null;
  publieLe: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Adresses collectées par le formulaire « Restez informé » du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes".
 */
export interface Abonne {
  id: number;
  email: string;
  langue?: ('fr' | 'en') | null;
  /**
   * Page d'origine de l'inscription (accueil, benin…)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Le code est enregistré en majuscules. La réduction s'applique sur le sous-total.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes-promo".
 */
export interface CodesPromo {
  id: number;
  /**
   * Enregistré en majuscules, quelle que soit la saisie
   */
  code: string;
  /**
   * Réduction en % sur le sous-total
   */
  reductionPct: number;
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brouillons".
 */
export interface Brouillon {
  id: number;
  token: string;
  etape?: number | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Épinglettes réservables. Le prix affiché aux visiteurs est celui saisi ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epinglettes".
 */
export interface Epinglette {
  id: number;
  /**
   * Identifiant stable, ex. pin-president
   */
  slug: string;
  nom: string;
  description?: string | null;
  /**
   * Prix de vente en FCFA, fixé par le comité. C'est ce montant qui est facturé.
   */
  prixFcfa: number;
  /**
   * Référence sur shop.toastmasters.org (ex. 5801), pour la commande groupée
   */
  refTi?: string | null;
  /**
   * Ex. /produits/pin-president.webp
   */
  photoUrl?: string | null;
  ordre?: number | null;
  /**
   * Décocher retire l'article de la vitrine
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Réservations d'épinglettes. La liste d'achat agrégée n'inclut que les réservations confirmées.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  /**
   * Référence lisible, ex. COT27-P0042
   */
  reference?: string | null;
  /**
   * Jeton aléatoire de la page de confirmation. Jamais l'identifiant, qui est énumérable.
   */
  token?: string | null;
  prenom: string;
  nom: string;
  email: string;
  telephone: string;
  club?: string | null;
  pays?: string | null;
  statut: 'en_attente' | 'confirmee' | 'commandee' | 'arrivee' | 'remise' | 'annulee';
  /**
   * Instantané figé à la réservation — ne pas modifier
   */
  lignes: {
    slug: string;
    nom: string;
    prixUnitaire: number;
    quantite: number;
    id?: string | null;
  }[];
  /**
   * Recalculé par le serveur depuis les prix du catalogue
   */
  totalFcfa: number;
  modePaiement?: ('sur_place' | 'fedapay' | 'virement') | null;
  fedapayTransactionId?: string | null;
  note?: string | null;
  payeeLe?: string | null;
  remiseLe?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'inscriptions';
        value: number | Inscription;
      } | null)
    | ({
        relationTo: 'paiements';
        value: number | Paiement;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'intervenants';
        value: number | Intervenant;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'editions';
        value: number | Edition;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'abonnes';
        value: number | Abonne;
      } | null)
    | ({
        relationTo: 'codes-promo';
        value: number | CodesPromo;
      } | null)
    | ({
        relationTo: 'brouillons';
        value: number | Brouillon;
      } | null)
    | ({
        relationTo: 'epinglettes';
        value: number | Epinglette;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  prenom?: T;
  nom?: T;
  email?: T;
  telephone?: T;
  pays?: T;
  ville?: T;
  club?: T;
  districtRole?: T;
  langue?: T;
  regimeAlimentaire?: T;
  besoinsAccessibilite?: T;
  premiereConference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscriptions_select".
 */
export interface InscriptionsSelect<T extends boolean = true> {
  participant?: T;
  categorie?: T;
  montant?: T;
  devise?: T;
  statut?: T;
  optionsSelectionnees?: T;
  codePromo?: T;
  nombreParticipants?: T;
  membres?:
    | T
    | {
        prenom?: T;
        nom?: T;
        email?: T;
        id?: T;
      };
  modePaiement?: T;
  canal?: T;
  qrToken?: T;
  checkedInAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paiements_select".
 */
export interface PaiementsSelect<T extends boolean = true> {
  inscription?: T;
  fournisseur?: T;
  referenceExterne?: T;
  montant?: T;
  devise?: T;
  statut?: T;
  payloadWebhook?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  titre?: T;
  resume?: T;
  type?: T;
  debut?: T;
  fin?: T;
  salle?: T;
  langue?: T;
  capacite?: T;
  intervenants?: T;
  supportUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intervenants_select".
 */
export interface IntervenantsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  titre?: T;
  bio?: T;
  pays?: T;
  photo?: T;
  keynote?: T;
  distinctions?:
    | T
    | {
        distinction?: T;
        id?: T;
      };
  reseaux?:
    | T
    | {
        plateforme?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  nom?: T;
  palier?: T;
  logo?: T;
  siteUrl?: T;
  description?: T;
  contreparties?:
    | T
    | {
        contrepartie?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions_select".
 */
export interface EditionsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  type?: T;
  description?: T;
  couverture?: T;
  publieLe?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  edition?: T;
  chapo?: T;
  corps?: T;
  auteur?: T;
  rubrique?: T;
  imageCouverture?: T;
  tempsLecture?: T;
  publieLe?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes_select".
 */
export interface AbonnesSelect<T extends boolean = true> {
  email?: T;
  langue?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes-promo_select".
 */
export interface CodesPromoSelect<T extends boolean = true> {
  code?: T;
  reductionPct?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brouillons_select".
 */
export interface BrouillonsSelect<T extends boolean = true> {
  token?: T;
  etape?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "epinglettes_select".
 */
export interface EpinglettesSelect<T extends boolean = true> {
  slug?: T;
  nom?: T;
  description?: T;
  prixFcfa?: T;
  refTi?: T;
  photoUrl?: T;
  ordre?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  reference?: T;
  token?: T;
  prenom?: T;
  nom?: T;
  email?: T;
  telephone?: T;
  club?: T;
  pays?: T;
  statut?: T;
  lignes?:
    | T
    | {
        slug?: T;
        nom?: T;
        prixUnitaire?: T;
        quantite?: T;
        id?: T;
      };
  totalFcfa?: T;
  modePaiement?: T;
  fedapayTransactionId?: T;
  note?: T;
  payeeLe?: T;
  remiseLe?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * La boutique est livrée fermée. Vérifiez les prix avant d'ouvrir les réservations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boutique".
 */
export interface Boutique {
  id: number;
  /**
   * Ouvre les réservations sur le site public
   */
  ouverte?: boolean | null;
  /**
   * Affiché aux visiteurs, sous le panier
   */
  delaiRemise?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boutique_select".
 */
export interface BoutiqueSelect<T extends boolean = true> {
  ouverte?: T;
  delaiRemise?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}